version: "3.8"

services:
  apache:
    build: ./apache
    container_name: apache_server
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    container_name: nginx_server
    volumes:
      - /home/ubuntu/:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - apache
